import { createMenuSection } from "@/modules/customer/homepage/lib/create-menu-item";
import type { MenuSection } from "@/modules/customer/homepage/types/menu-section";

export const HOME_MENU_SECTIONS: MenuSection[] = [
  createMenuSection("menu-makanan", "MENU MAKANAN", [
    "Nasi Putih Porsi",
    "Nasi Putih Boboko",
    "Nasi Liwet Porsi",
    "Nasi Liwet Boboko",
    "Cah Kangkung Biasa",
    "Cah Kangkung Terasi",
    "Cah Toge",
    "Sayur Asem",
    "Sambal Dadakan",
    "Sambel Goreng",
    "Tempe Goreng / Potong",
    "Tempe Porsi",
    "Tahu Goreng / Potong",
    "Tahu Porsi",
    "Tempe Tahu Mix",
    "Telor Dadar",
    "Telor Mata Sapi",
    "Semur Jengkol",
    "Jengkol Balado",
    "Jengkol Goreng",
    "Terong Balado",
    "Jamur Crispy",
    "Karedok",
  ]),
  createMenuSection("menu-ikan-lauk", "MENU IKAN & LAUK UTAMA", [
    "Ayam Bakar / Goreng 1 Potong",
    "Ayam Bakar / Goreng 1 Ekor",
    "Ayam Saus Tiram",
    "Ayam Saus Padang",
    "Ayam Asam Manis",
    "Ayam Hot Plate",
    "Ayam Pecak",
    "Cumi Goreng Tepung",
    "Cumi Saus Tiram",
    "Cumi Saus Padang",
    "Cumi Asam Manis",
    "Cumi Hot Plate",
    "Udang Goreng Tepung",
    "Udang Saus Tiram",
    "Udang Saus Padang",
    "Udang Asam Manis",
    "Udang Hot Plate",
    "Gurame Bakar",
    "Gurame Goreng",
    "Gurame Pecak",
    "Gurame Saos Tiram",
    "Gurame Saos Padang",
    "Gurame Asam Manis",
    "Pecak Bandeng",
    "Sop Iga",
    "Iga Bakar",
    "Pepes Peda",
    "Tumis Peda",
  ]),
  createMenuSection("menu-cemilan", "MENU CEMILAN", [
    "Kerupuk",
    "Kentang Goreng",
    "Nugget",
    "Otak Otak Biasa",
    "Sosis Goreng",
    "Sosis Bakar",
    "Tempe Mendoan",
    "Dimsum",
    "Indomie",
    "Indomie + Telor",
  ]),
  createMenuSection("menu-minuman", "MENU MINUMAN", [
    "Air Mineral",
    "Es Gaul",
    "Es Kuwut Timun",
    "Es Melger",
    "Es Jeruk",
    "Es Teh Manis",
    "Es Teh Tawar",
    "Teh Manis Hangat",
    "Teh Tawar Hangat",
    "Es Lemon Tea",
    "Lemon Tea Hangat",
    "Es Batu Kristal",
    "Es Coffee",
    "Es Moccacino",
    "Es Chocolatos",
    "Es Susu",
    "Indocafe",
    "Luwak Coffee",
    "Kopi Hitam",
    "Kopi Good Day",
    "Jus Alpukat",
    "Jus Strawberry",
    "Jus Melon",
    "Jus Jambu Biji",
    "Jus Apel",
    "Jus Buah Naga",
    "Susu Panas",
    "Teh Botol",
  ]),
  createMenuSection("menu-lain", "MENU LAIN", ["Soto Ayam", "Soto Daging"]),
  createMenuSection(
    "menu-paket",
    "MENU PAKET",
    [
      "Paket 24K (Tanpa Minuman)",
      "Paket 26K (Air Mineral)",
      "Paket 27K (Es Teh Manis)",
      "Paket 28K (Nasi Liwet)",
    ],
    {
      "Paket 24K (Tanpa Minuman)": 24000,
      "Paket 26K (Air Mineral)": 26000,
      "Paket 27K (Es Teh Manis)": 27000,
      "Paket 28K (Nasi Liwet)": 28000,
    },
  ),
];
